# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200909_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
    ]
