# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-10 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200910_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='ایران', max_length=120),
        ),
    ]
