# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200903_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
