# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-10 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200903_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=20),
        ),
    ]
